name: GitHub Metrics

on:
  # รันอัตโนมัติทุกวัน 07:00 ตามเวลาไทย
  schedule: [{ cron: "0 0 * * *" }]
  # กดรันเองได้จากแท็บ Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # ให้สิทธิ์เขียนไฟล์ผลลัพธ์กลับเข้ารีโป
    steps:
      - name: Generate profile metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ChavaphonBoonchan
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Bangkok
          filename: github-metrics.svg
